# Generated by Django 4.1 on 2022-08-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lumpia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(choices=[('B', 'Beef'), ('C', 'Chicken'), ('F', 'Fish'), ('P', 'Pork'), ('T', 'Turon'), ('V', 'Vegetarian')], default='B', max_length=1)),
                ('fillings', models.TextField(max_length=250)),
                ('review', models.TextField(max_length=250)),
            ],
        ),
    ]
