# Generated by Django 4.1 on 2022-08-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dessert'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumpia',
            name='desserts',
            field=models.ManyToManyField(to='main_app.dessert'),
        ),
    ]
